# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57ef4254adaec54f47b32e5f8b470a027a495c9d403be2e4f15fa8b7044b00f6e49b442f213bb94fa5b9b798fb8c8de716e7ef7e85110ec2f2408efdc9b662da

test:
  secret_key_base: 49679c7eccce1bee39b131052ad83b790928a381897a122da63e99411c4551521b556305afc2b97fc5b5430ebc6d2a8d90e3a8a7255c409236731a280984e5a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
